"""remove_payment_update_subscriptions

Revision ID: ce05435f23b0
Revises: baa03742b524
Create Date: 2026-06-01 18:44:29.691513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce05435f23b0'
down_revision: Union[str, None] = 'baa03742b524'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('subscriptions_offer_id_fkey'), 'subscriptions', type_='foreignkey')
    op.drop_column('subscriptions', 'monthly_price')
    op.drop_column('subscriptions', 'offer_id')
    op.drop_column('settings', 'paypal_email')
    op.drop_column('settings', 'vodafone_cash_number')
    op.drop_table('payments')
    op.drop_table('subscription_offers')
    op.drop_table('subscription_requests')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('offer_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('subscriptions', sa.Column('monthly_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('subscriptions_offer_id_fkey'), 'subscriptions', 'subscription_offers', ['offer_id'], ['id'], ondelete='SET NULL')
    op.add_column('settings', sa.Column('vodafone_cash_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('settings', sa.Column('paypal_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_table('payments',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('request_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('payment_method', postgresql.ENUM('PAYPAL', 'VODAFONE_CASH', name='payment_method'), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('receipt_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', name='payment_status'), autoincrement=False, nullable=False),
    sa.Column('admin_note', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('reviewed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['subscription_requests.id'], name=op.f('payments_request_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('payments_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('payments_pkey'))
    )
    op.create_table('subscription_requests',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING_PRICING', 'PRICE_SENT', 'WAITING_PAYMENT', 'PAYMENT_REVIEW', 'APPROVED', 'REJECTED', name='request_status'), autoincrement=False, nullable=False),
    sa.Column('admin_note', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('subscription_requests_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('subscription_requests_pkey'))
    )
    op.create_table('subscription_offers',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('request_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('monthly_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('token_limit', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('offer_note', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_accepted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['subscription_requests.id'], name=op.f('subscription_offers_request_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('subscription_offers_pkey'))
    )
    # ### end Alembic commands ###
