"""Add summary to chats and interests to users

Revision ID: 27d7cc489cac
Revises: 5c471712904e
Create Date: 2026-06-04 14:36:03.047848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27d7cc489cac'
down_revision: Union[str, None] = '5c471712904e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('summary', sa.String(), nullable=True))
    op.add_column('users', sa.Column('interests_summary', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'interests_summary')
    op.drop_column('chats', 'summary')
    # ### end Alembic commands ###
