"""add project_id to chats

Revision ID: 5c471712904e
Revises: 2a1efd4281e0
Create Date: 2026-06-04 13:54:34.907850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c471712904e'
down_revision: Union[str, None] = '2a1efd4281e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('project_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'chats', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_column('chats', 'project_id')
    # ### end Alembic commands ###
